[project]
name = "wine-list-etl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marimo>=0.14.7",
    "pandas>=2.3.0",
    "pdfplumber>=0.11.7",
]
