[project]
name = "wine-spectator-australia-wine-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nest-asyncio>=1.6.0",
    "playwright>=1.52.0",
]
