/*
Use to load the csv files generated by pdf_parser.py
* */
create table if not exists pagesraw as (
    select
        page_number as page_num,
        * exclude (page_number)
    from 'pagesraw_path'
);

create table if not exists rect as (
    select
        page_number as page_num,
        row_number() over () as rect_num_tot,
        row_number() over (partition by page_number) as rect_num,
        x0,
        y0,
        x1,
        y1,
        width,
        height,
        pts,
        linewidth
    from
        read_csv('rect_path')
);
